export enum NotificationType {
  BOOKING_SUCCESS = 'BOOKING_SUCCESS',
  INVITED_TO_BOOKING = 'INVITED_TO_BOOKING',
  NEW_BOOKING_FOR_OWNER = 'NEW_BOOKING_FOR_OWNER',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
}
